name = "UseAll"
uuid = "edbe3dbe-4909-5f9e-bb65-679d27932c2a"
authors = ["Patrick Häcker"]
version = "0.1.1"

[workspace]
projects = ["test", "docs"]

[weakdeps]
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[extensions]
UseAllREPLExt = "REPL"
UseAllReviseExt = "Revise"

[compat]
REPL = "1.10"
Revise = "3"
julia = "1.10"
