[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LiveServer = "16fef848-5104-11e9-1b77-fb7a48bbb589"
UseAll = "edbe3dbe-4909-5f9e-bb65-679d27932c2a"

[sources]
UseAll = {path = "/home/hp74lr/devel/diverse/UseAll.jl"}

[compat]
Documenter = "1"
