name: Reusable test

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  workflow_call:
    inputs:
      version:
        required: false
        type: string
        default: "1"
      os:
        required: false
        type: string
        default: ubuntu-latest
      arch:
        required: false
        type: string
        default: x64
      allow_failure:
        required: false
        type: boolean
        default: false
      run_codecov:
        required: false
        type: boolean
        default: false
    secrets:
      codecov_token:
        required: true

jobs:
  test:
    name: Julia ${{ inputs.version }} - ${{ inputs.os }} - ${{ inputs.arch }} - ${{ github.event_name }}
    runs-on: ${{ inputs.os }}
    continue-on-error: ${{ inputs.allow_failure }}
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v6
      - uses: julia-actions/setup-julia@v2.7.0
        with:
          version: ${{ inputs.version }}
          arch: ${{ inputs.arch }}
      - name: Use Julia cache
        uses: julia-actions/cache@v3
        with:
          delete-old-caches: false
      - name: Ensure General registry
        run: |
          julia --color=yes -e 'import Pkg; isempty(Pkg.Registry.reachable_registries()) && Pkg.Registry.add(Pkg.RegistrySpec(name="General"))'
      - name: Instantiate test environment
        run: |
          julia --project=test --color=yes -e 'import Pkg; Pkg.develop(Pkg.PackageSpec(path=pwd())); Pkg.instantiate()'
      - name: Run tests
        run: |
          if [ "${{ inputs.run_codecov }}" = "true" ]; then
            julia --project=test --color=yes --code-coverage=user test/runtests.jl
          else
            julia --project=test --color=yes test/runtests.jl
          fi
      - uses: julia-actions/julia-processcoverage@v1
        if: ${{ inputs.run_codecov }}
      - uses: codecov/codecov-action@v4
        if: ${{ inputs.run_codecov }}
        with:
          file: lcov.info
          token: ${{ secrets.codecov_token }}
